### ISSUE TITLE
Example of lazyLoad

### ISSUE THREAD

**Issue by milosmalic** [patternfly/patternfly-bootstrap-treeview#112]
Is there an example of lazyLoad tree somewhere to see. I am struggling a bit with format of Json to return from ajax function to display to render.

Thanks!

**Comment by skateman** [comment]
Here you can see how we're using it: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/assets/javascripts/miq_tree.js#L556-L571

The format should be the same as the input format of the tree, i.e. an array of objects. You can see it in the README.
