### ISSUE TITLE
hideCheckbox not working

### ISSUE THREAD

**Issue by DerPeiler1986** [patternfly/patternfly-bootstrap-treeview#17]
Hi all, 

i using the treeview with checkboxes but wan't to hide the checkbox for the parent and firs chil node. I added hideCheckbox = true but there isn't any effect. 

Please find a snipped below. 

`<script type="text/javascript">
  		$(function() {

        var defaultData = [
          {
	    hideCheckbox: true,
            text: 'Main Categorie',
            nodes: [
              {
		hideCheckbox: true,  
		text: 'Sub Categorie',
                nodes: [
                  {
                    text: 'Option 1',
                  },
                  {
                    text: 'Option 2',
                  },
		  {
	            text: 'Option 3',
		   },
		  {
		    text: 'Option 4',
		   }
                ]
              },
                ]
              }
            ]
          },

		var $checkableTree = $('#treeview-checkable').treeview({
          levels: 1,
		  data: defaultData,
          showIcon: false,
          showCheckbox: true,
          onNodeChecked: function(event, node) {
            $('#selected-option').prepend('<p>' + node.text + ' was checked</p>');
          },
          onNodeUnchecked: function (event, node) {
            $('#selected-option').prepend('<p>' + node.text + ' was unchecked</p>');
          }
        });
	});`

**Comment by skateman** [comment]
@DerPeiler1986 you probably missed the `checkable` global attribute. Please verify if that works and I'll update the documentation.

**Comment by DerPeiler1986** [comment]
please help me in detail, where i need to set the global attribute?

**Comment by skateman** [comment]
Hm, now I checked and you don't need the `checkable` attribute. Also your example seems to work for me. Are you for sure using `patternfly-bootstrap-treeview`? We are a fork as the development of the original `bootstrap-treeview` is stalled. All the changes introduced here are available as [PRs in the upstream repo](https://github.com/jonmiles/bootstrap-treeview/pulls/skateman) and hopefully they will be merged in the future...
