### ISSUE TITLE
Determine nodeUnselected originator/sender

### ISSUE THREAD

**Issue by cocowalla** [patternfly/patternfly-bootstrap-treeview#18]
`nodeUnselected` is called when a node is unselected, but is also called when a node is unselected *because* another node was selected.

I'm using the tree in a sort of master-detail setup, where selecting a tree node loads some detail data using ajax.

So when a node is selected, I want to load data. But when a node is *unselected* I want to remove previously loaded data - but only if a node was unselected by the *user*. The problem is that I can't find any way to differentiate between a node 'really' being unselected, and a a node being unselected 'automatically' because another has been selected.

Is there any way to determine the originator/sender of the `nodeUnselected` event?

**Comment by skateman** [comment]
@cocowalla maybe it's a bad idea but after the first read I would try write an event listener that can catch multiple events. This listener might be able to determine which type of unselect was fired. But I will take a deeper look into this problem later...

**Comment by cocowalla** [comment]
@skateman I see you closed this - were you able to take a look at the issue?

**Comment by skateman** [comment]
@cocowalla umm, I auto-closed everything from 2016. If this still an issue, please reopen it...
