### ISSUE TITLE
addnode need mousehover event

### ISSUE THREAD

**Issue by 3xxx** [patternfly/patternfly-bootstrap-treeview#22]
wonderful job，thank you.
I use add/remov/update method。
Can you provide this function, when the mouse moves to the node, add、remove and update custom image display.
like 
![image](https://cloud.githubusercontent.com/assets/10678867/22195141/704b2060-e181-11e6-8f8a-f231866a46d5.png)

[http://img.blog.csdn.net/20160109120114742](url)
[http://img.blog.csdn.net/20160109121325104](url)
[http://blog.csdn.net/wangjingna/article/details/50487111](url)

**Comment by newdebug** [comment]
@3xxx 这个很容易做啊，我新手折腾了一晚上搞定了~
add add/edit/remove event buttons:
**first**:
```
Tree.prototype._template = {
//...
button: {
add: $(<button class="btn node-hidden"></button>),
edit: $(<button class="btn node-hidden"></button>),
remove: $(<button class="btn node-hidden"></button>)
//...
}
```
**second**:
```
Tree.prototype._renderNode = function (node, previousNode) {
//...
node.$el.append(this._template.button.add.clone());
node.$el.append(this._template.button.edit.clone());
node.$el.append(this._template.button.remove.clone());
node.$el.mouseenter(function(){
//...
node.$el.mouseenter(function(){
node.$el.children('button.btn').removeClass('node-hidden');
}).mouseleave(function(){
ode.$el.children('button.btn').addClass('node-hidden');
});
//...
```
**third**(option):
Add onAddButtonClicked/onEidtButtonClicked/onRemoveButtonClicked evnets to _default.settings{} and other place , just likes onNodeUnchecked,onNodeUnselected etc.
then,
$('#tree').treeview({
data:[],
onAddButtonClicked:function(event, node){...},
//...
});
**(end)**

**Comment by wang-ya-ning** [comment]
onAddButtonClicked:function(event, node){...}这里面该怎么写

**Comment by Javaldh** [comment]
@wang-ya-ning 
看看这个，可以参考下http://blog.csdn.net/wangjingna/article/details/50487111

**Comment by wang-ya-ning** [comment]
谢谢已经解决了




------------------ 原始邮件 ------------------
发件人: "Javaldh";<notifications@github.com>;
发送时间: 2017年7月23日(星期天) 上午10:21
收件人: "patternfly/patternfly-bootstrap-treeview"<patternfly-bootstrap-treeview@noreply.github.com>; 
抄送: "王亚宁"<3148770641@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [patternfly/patternfly-bootstrap-treeview] addnode needmousehover event (#22)




@wang-ya-ning
 看看这个，可以参考下http://blog.csdn.net/wangjingna/article/details/50487111

**Comment by Javaldh** [comment]
@wang-ya-ning 代码勒#

**Comment by skateman** [comment]
Hi,

I think this feature is very specific and should be implemented outside using jQuery. The nodes are accessible by CSS selectors and so you can define your own `hover` event handlers.

**Comment by wang-ya-ning** [comment]
using ztree can do whatever you want

**Comment by Sunny8675** [comment]
@newdebug 可以发一下这个代码吗？

**Comment by rapasae** [comment]
Thank you for your code, buttons are shown/hidden correctly but no event is triggered when buttons are clicked (onAddButtonClicked:function(event, node){...})
