### ISSUE TITLE
I have a "updateNode" bug

### ISSUE THREAD

**Issue by 3xxx** [patternfly/patternfly-bootstrap-treeview#23]
Hi, when I use this method:$('#tree').treeview('updateNode', [ node, newNode, { silent: true } ]);
after update,the node‘s sons disappeared。Have you met before？

**Comment by merciqiao** [comment]
我也遇到这个问题了,你解决了没

**Comment by 3xxx** [comment]
http://download.csdn.net/download/qq812858143/9801416

**Comment by mumuxizzz** [comment]
> http://download.csdn.net/download/qq812858143/9801416
the link is unavaible

**Comment by mumuxizzz** [comment]
Anyone else who has this trouble can refer [this repository](https://github.com/merciqiao/bootstrap-treeview-demo).
