### ISSUE TITLE
TreeView not working with showTags

### ISSUE THREAD

**Issue by PeteDurst** [patternfly/patternfly-bootstrap-treeview#37]
Hi,

if you set showTags to true the following exception occurs.
I made a [fiddle ](https://jsfiddle.net/wpp6062h/3/)

jQuery.Deferred exception: Cannot read property '0' of undefined TypeError: Cannot read property '0' of undefined
    at Tree.addTag (https://rawgit.com/patternfly/patternfly-bootstrap-treeview/master/dist/bootstrap-treeview.js:975:29)

Problem is in line 977 tagsClass is undefinded.
`typeof node.tagsClass[id] === 'string' ?`

hope this helps.

**Comment by skateman** [comment]
You probably linked a wrong fiddle, could you please update it? Thanks!

**Comment by PeteDurst** [comment]
Thank you. Issue updated.
[working fiddle](https://jsfiddle.net/wpp6062h/3/)

**Comment by skateman** [comment]
Release pushed, should work
