### ISSUE TITLE
Vers. 2.1.2 completely breaks my tree, vers. 2.1.1 is ok

### ISSUE THREAD

**Issue by marcodelpercio** [patternfly/patternfly-bootstrap-treeview#41]
Hello,

I had to debug the 'checkNode' method and since I was running vers. 2.1.1 I thoguht it might have been a good idea to update this library to the latest version. However as soon as I reloaded the page the tree was totally broken, only the first noce is coming up with a weird border and no children when trying to expand...same happens with vers. 2.1.2.
I looked at the dates and as soon as I tried vers. 2.1.0 my tree works again perfectly. I can debug that version however I still cannot update to the latest!
Is there any major breaking change from 2.1.1 to 2.1.2 ?? 
Take a look at what happens with the very same code:

![with_vers 2 1 1](https://user-images.githubusercontent.com/7857757/27027260-988ac978-4f58-11e7-8d6e-215638010743.png)

![with_vers 2 1 2](https://user-images.githubusercontent.com/7857757/27027259-987db7ba-4f58-11e7-8164-1da2015f9d27.png)

The code to get that tree hasn't changed, it's the same for both and yet it produces a highly different result:
```
jQuery("#outfitsProductsTree", documentContext).treeview({
      data: treeviewData,
      hierarchicalCheck: true,
      expandIcon:"fa fa-chevron-right",
      collapseIcon:"fa fa-chevron-down",
      loadingIcon:"fa fa-clock-o",
      emptyIcon:"fa",
      checkedIcon: 'fa fa-check-square-o',
      uncheckedIcon: 'fa fa-square-o',
      showCheckbox: true,
      showTags: true,
      partiallyCheckedIcon: 'fa fa-minus-square-o'        
});
```
and obviously **treeviewData** is always the same structure for both

Many thanks

**Comment by skateman** [comment]
Hi,

there is an issue with tagging and there is a [dispute](https://github.com/patternfly/patternfly-bootstrap-treeview/pull/39) about how to fix it. I will update this issue when it's sorted out and also push a new version.

**Comment by marcodelpercio** [comment]
Thank you very much!

I was going mad and couldn't understand if I had broken anything myself :-) until I figured out that the same code with 2 versions was producing totally different results.

Cheers

**Comment by skateman** [comment]
2.1.4 was released
