### ISSUE TITLE
how to load data after click the expand icon?

### ISSUE THREAD

**Issue by zhizhi555555** [patternfly/patternfly-bootstrap-treeview#49]
if three have a tree data, how to asyn the data？such as it click expand icon ,and load the data from db.
is there have the solved method?

**Comment by skateman** [comment]
Hi,

you will have to set a [lazyLoad](https://github.com/patternfly/patternfly-bootstrap-treeview#lazyload-1) function to load the data and set the [lazyLoad](https://github.com/patternfly/patternfly-bootstrap-treeview#lazyload) attribute of the desired nodes to `true`.

```js
$(...).treeview({
  ...
  lazyLoad: function(node, display) {
    data = ajax(node); // write your own ajax request that returns the subtree of node
    display(data); // the display function is provided, you just need to pass the data
  };
})
```

**Comment by zhizhi555555** [comment]
ok.thanks for help


Sent from Mail Master
On 07/31/2017 15:08, Halász Dávid wrote:

Hi,

you will have to set a lazyLoad function to load the data and set the lazyLoad attribute of the desired nodes to true.

$(...).treeview({
  ...lazyLoad:function(node, display) {
    data =ajax(node); // write your own ajax request that returns the subtree of nodedisplay(data); // the display function is provided, you just need to pass the data
  };
})
