### ISSUE TITLE
Can´t collapse

### ISSUE THREAD

**Issue by abelduran1** [patternfly/patternfly-bootstrap-treeview#54]
Hi, my name is Abel , I have implemented this library in my app but the plus and minus icons not appear, so is impossible to collapse the nodes. 
Thanks in advance.

![image](https://user-images.githubusercontent.com/17276538/29999233-f0571f20-9040-11e7-8307-e2f5919fdc4f.png)

**Comment by abelduran1** [comment]
I have fix it. The problem was i had installed the bootstrap 4.0.0 and I now I have installed the 3.3.7 and all works. Maybe incompatibilities problems with the new version of bootstrap??

**Comment by kaaxsh** [comment]
https://getbootstrap.com/docs/4.0/migration/#components
