### ISSUE TITLE
Having different colors (back & fore) for levels ?

### ISSUE THREAD

**Issue by ernest33** [patternfly/patternfly-bootstrap-treeview#55]
Hello,
Could be really cool to be able to specify backColor (all colors related) as an array ['#fff', '#0f0'].
The first one for the first level, the second for the second and so on. And in the case you have only defined 3 colors all level upper 3 use the third color.

Regards
Philippe

**Comment by skateman** [comment]
@ernest33 can't you do this entirely in the CSS?

**Comment by ernest33** [comment]
@skateman Yes this will be possible :-) But as a lazy man i found this could be a good addition ;-)

**Comment by skateman** [comment]
Well, I would not want to add such a very specific feature if it can be solved much easier. The plan is to reduce the current amount of CSS generated by JS anyway. Sorry...
