### ISSUE TITLE
method addNode

### ISSUE THREAD

**Issue by aamsoh** [patternfly/patternfly-bootstrap-treeview#56]
Hi, 

How I can use addNode method in treeview. any help will be highly appreciated. 

Regards, 

Aamir 

![image](https://user-images.githubusercontent.com/32142891/30661824-2f2d47e2-9e56-11e7-8f0a-b2bdcd3a1d27.PNG)

**Comment by skateman** [comment]
If this is not [self-describing](https://github.com/patternfly/patternfly-bootstrap-treeview#addnodenodes-parentnode-index-options) enough, here's an example:

```js
var allNodes = $('#tree').treeview.getNodes();
var nodesToAdd = ...; // array of the nodes to add
// adds the nodesToAdd as the children of the fourth node
$('#tree').treeview('addNode', [ nodestoAdd, allNodes[3] ]);
```
