### ISSUE TITLE
Can it support context menu?

### ISSUE THREAD

**Issue by rogertangcn** [patternfly/patternfly-bootstrap-treeview#59]
I have used bootstrap treeview for quite a while, it was pretty good until recent. We have a requirement that needs a pop up menu when right clicking the node. Is it possible to support that? Thanks.

**Comment by skateman** [comment]
Hi,

this is an interesting idea, but I would like to keep the codebase as simple as possible. You could try a library like [this one](https://swisnl.github.io/jQuery-contextMenu/demo.html), all the nodes are accessible using CSS selectors, so you can define menu items on them. Using the `.findNodes()` or `.getNodes()` you can even specify the context menu inside the tree.

I hope this helps.

**Comment by rogertangcn** [comment]
Thanks for prompt response.

Yeah, that's the idea I've explored. And, as the project of mine uses bootstrap, I chose [bootstrap-menu](https://github.com/dgoguerra/bootstrap-menu) instead. Here is how I ended up doing. Hope this help anyone seeking to do the same as mine. 

```
$("#treeview").treeview({
  //...

  onNodeRendered: function(event, node) {
    new BootstrapMenu(`#${node.id}`, {
        menuEvent: 'right-click',
        menuSource: 'mouse',
        menuPosition: 'belowLeft', // default value, can be omitted
        actions: [{
            name: 'Action',
            onClick: function(element) {
                console.log("click:", element);
            }
        }]
    });
  },

  //...
});
```
