### ISSUE TITLE
use of Fontawesome not possible

### ISSUE THREAD

**Issue by MaggiWuerze** [patternfly/patternfly-bootstrap-treeview#73]
if you have fontawesome included in your page and create nodes with fontawesome classes instead of glyphicons (removed in later Bootstrap versions) it either displays nothing, squares or ignores the classes 
 entirely and creates the nodes with standard glyphicon classes instead.

**Comment by skateman** [comment]
@MaggiWuerze can you please provide a working reproducer on codepen or jsfiddle? Thanks

**Comment by MaggiWuerze** [comment]
can do, but i just tried to do it via the `$('#tree').treeview()` method instead of node json data and the classes are accepted from there. only the icons for collapse and expand are not switching, it always shows the expand icon.

**Comment by skateman** [comment]
`fas fa-caret-down` -> `fa-caret-down`
