### ISSUE TITLE
findNode based on id?

### ISSUE THREAD

**Issue by amunter** [patternfly/patternfly-bootstrap-treeview#74]
Is there a way to find a node based upon an arbitrary attribute value set in the node like, for instance, id?  I can't seem to do it.  I'd like to programmatically select a node based on id.

I'm trying to use it to track a hierarchy of locations, like "Room A->Gray Cabinet->Shelf 2" etc., but many of them will have similar names, which the search method uses, with different ids.

**Comment by skateman** [comment]
You need to iterate through `getNodes()`

**Comment by amunter** [comment]
Thanks for the tip.  Will try that.
