### ISSUE TITLE
Reload the tree without affecting open/closed nodes

### ISSUE THREAD

**Issue by dset0x** [patternfly/patternfly-bootstrap-treeview#77]
Hello. I wonder if there is a way of reloading a tree (currently I call `$(..).treeview(..)` again) without closing/opening already open/close nodes, thus making the least amount of modifications to the user's current view.

I can imagine writing logic that checks the status of all the nodes and then sets that status again every time rendering is finished, but having a convenient `refresh` method would be ideal.

**Comment by skateman** [comment]
Hi, as you're providing the data to the tree, you can update the data as you expand/collapse. We're doing it using `sessionStorage`: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/assets/javascripts/miq_tree.js#L441-L456
