### ISSUE TITLE
Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead

### ISSUE THREAD

**Issue by Thassya** [patternfly/patternfly-bootstrap-treeview#97]
I get this message on my browser (Opera) and I did not find any document.registerElement on jstree.js. 

`jstree.js:7424 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.`

`jstree.js:7424`

**Comment by skateman** [comment]
Hello @Thassya, thanks for your first issue. Unfortunately, I am not able to find the mentioned `jstree.js` in our codebase, is it possible that you're loading it from somewhere else? I need a little bit of more context about you problem to be able to help you.

**Comment by Thassya** [comment]
@skateman maybe a print would help 
[http://prntscr.com/micg21](http://prntscr.com/micg21)

**Comment by skateman** [comment]
Well, not much :disappointed: I would like to see what's on the 7424th line in the `jstree.js` file and maybe a few lines before and after. But I'm afraid that the code is not from us, the `registerElement` causing the error is nowhere in our codebase.

**Comment by Thassya** [comment]
I am sorry @skateman I remove the jstree and that's ok! I will delete this issue
